-- LumoroX Park — portable database schema.
-- Generated by scripts/export-schema.sh. Run this in the SQL editor of
-- your own Supabase project (once, on an empty project).

create extension if not exists "uuid-ossp";
create extension if not exists postgis;
create extension if not exists pgcrypto;

-- ============ ENUM TYPES ============
do $$ begin create type public.app_role as enum ('admin', 'moderator', 'user'); exception when duplicate_object then null; end $$;

-- ============ TABLES ============
create table if not exists public.activity_log (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  action text not null,
  reference_id uuid,
  metadata jsonb,
  created_at timestamp with time zone not null default now()
);
create table if not exists public.availability_slots (
  id uuid not null default gen_random_uuid(),
  space_id uuid not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  is_booked boolean not null default false
);
create table if not exists public.bookings (
  id uuid not null default gen_random_uuid(),
  space_id uuid not null,
  renter_id uuid not null,
  host_id uuid not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  total_price numeric(10,2) not null,
  status text not null default 'pending'::text,
  payment_status text not null default 'unpaid'::text,
  stripe_session_id text,
  qr_checkin_code text,
  checked_in_at timestamp with time zone,
  checked_out_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  platform_fee numeric not null default 0,
  reservation_fee numeric not null default 0,
  host_earning numeric not null default 0,
  amount_charged numeric not null default 0,
  paddle_transaction_id text,
  cancelled_at timestamp with time zone,
  cancelled_by uuid,
  cancellation_reason text,
  refund_amount numeric not null default 0,
  paddle_refund_id text,
  earnings_clear_at timestamp with time zone,
  earnings_released_at timestamp with time zone,
  hold_expires_at timestamp with time zone
);
create table if not exists public.dispute_events (
  id uuid not null default gen_random_uuid(),
  dispute_id uuid not null,
  actor_id uuid,
  from_status text,
  to_status text not null,
  note text,
  created_at timestamp with time zone not null default now()
);
create table if not exists public.disputes (
  id uuid not null default gen_random_uuid(),
  booking_id uuid not null,
  raised_by uuid not null,
  reason text,
  status text not null default 'open'::text,
  admin_notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);
create table if not exists public.host_wallets (
  host_id uuid not null,
  lifetime_earnings numeric not null default 0,
  available_balance numeric not null default 0,
  pending_payout numeric not null default 0,
  total_paid_out numeric not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  pending_clearance numeric not null default 0
);
create table if not exists public.messages (
  id uuid not null default gen_random_uuid(),
  booking_id uuid not null,
  sender_id uuid not null,
  body text not null,
  read_at timestamp with time zone,
  created_at timestamp with time zone not null default now()
);
create table if not exists public.notifications (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  kind text not null,
  title text not null,
  body text,
  link text,
  booking_id uuid,
  read_at timestamp with time zone,
  created_at timestamp with time zone not null default now()
);
create table if not exists public.parking_spaces (
  id uuid not null default gen_random_uuid(),
  host_id uuid not null,
  title text not null,
  description text,
  address text not null,
  location geography(Point,4326),
  price_per_hour numeric(10,2) not null,
  price_per_day numeric(10,2),
  has_camera boolean not null default false,
  has_sensor boolean not null default false,
  is_gated boolean not null default false,
  is_covered boolean not null default false,
  has_ev_charging boolean not null default false,
  vehicle_types text[] not null default ARRAY['car'::text],
  photos text[] not null default ARRAY[]::text[],
  is_active boolean not null default true,
  live_occupancy_status text not null default 'unknown'::text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  cancellation_policy text not null default 'moderate'::text
);
create table if not exists public.payout_requests (
  id uuid not null default gen_random_uuid(),
  host_id uuid not null,
  amount numeric not null,
  status text not null default 'pending'::text,
  method text not null default 'bank'::text,
  account_holder text,
  account_number text,
  bank_code text,
  bank_name text,
  is_automatic boolean not null default false,
  admin_notes text,
  requested_at timestamp with time zone not null default now(),
  processed_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);
create table if not exists public.profile_contacts (
  user_id uuid not null,
  phone text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);
create table if not exists public.profiles (
  id uuid not null,
  full_name text,
  avatar_url text,
  is_host boolean not null default false,
  rating numeric(2,1) not null default 5.0,
  total_bookings integer not null default 0,
  trust_score integer not null default 100,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);
create table if not exists public.reviews (
  id uuid not null default gen_random_uuid(),
  booking_id uuid not null,
  reviewer_id uuid not null,
  reviewee_id uuid not null,
  space_id uuid,
  rating integer not null,
  comment text,
  created_at timestamp with time zone not null default now()
);
create table if not exists public.subscriptions (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  paddle_subscription_id text not null,
  paddle_customer_id text not null,
  product_id text not null,
  price_id text not null,
  status text not null default 'active'::text,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean default false,
  environment text not null default 'sandbox'::text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
create table if not exists public.support_tickets (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  name text not null,
  email text not null,
  category text not null default 'general'::text,
  subject text not null,
  message text not null,
  status text not null default 'open'::text,
  admin_notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);
create table if not exists public.user_roles (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  role app_role not null,
  created_at timestamp with time zone not null default now()
);
create table if not exists public.wallet_transactions (
  id uuid not null default gen_random_uuid(),
  host_id uuid not null,
  booking_id uuid,
  payout_id uuid,
  kind text not null,
  amount numeric not null,
  balance_after numeric not null default 0,
  note text,
  created_at timestamp with time zone not null default now()
);

-- ============ CONSTRAINTS ============
alter table public.bookings add constraint bookings_qr_checkin_code_key UNIQUE (qr_checkin_code);
alter table public.subscriptions add constraint subscriptions_paddle_subscription_id_key UNIQUE (paddle_subscription_id);
alter table public.user_roles add constraint user_roles_user_id_role_key UNIQUE (user_id, role);
alter table public.activity_log add constraint activity_log_pkey PRIMARY KEY (id);
alter table public.availability_slots add constraint availability_slots_pkey PRIMARY KEY (id);
alter table public.bookings add constraint bookings_pkey PRIMARY KEY (id);
alter table public.dispute_events add constraint dispute_events_pkey PRIMARY KEY (id);
alter table public.disputes add constraint disputes_pkey PRIMARY KEY (id);
alter table public.host_wallets add constraint host_wallets_pkey PRIMARY KEY (host_id);
alter table public.messages add constraint messages_pkey PRIMARY KEY (id);
alter table public.notifications add constraint notifications_pkey PRIMARY KEY (id);
alter table public.parking_spaces add constraint parking_spaces_pkey PRIMARY KEY (id);
alter table public.payout_requests add constraint payout_requests_pkey PRIMARY KEY (id);
alter table public.profile_contacts add constraint profile_contacts_pkey PRIMARY KEY (user_id);
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.reviews add constraint reviews_pkey PRIMARY KEY (id);
alter table public.subscriptions add constraint subscriptions_pkey PRIMARY KEY (id);
alter table public.support_tickets add constraint support_tickets_pkey PRIMARY KEY (id);
alter table public.user_roles add constraint user_roles_pkey PRIMARY KEY (id);
alter table public.wallet_transactions add constraint wallet_transactions_pkey PRIMARY KEY (id);
alter table public.activity_log add constraint activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.availability_slots add constraint availability_slots_space_id_fkey FOREIGN KEY (space_id) REFERENCES parking_spaces(id) ON DELETE CASCADE;
alter table public.bookings add constraint bookings_space_id_fkey FOREIGN KEY (space_id) REFERENCES parking_spaces(id);
alter table public.bookings add constraint bookings_host_id_fkey FOREIGN KEY (host_id) REFERENCES profiles(id);
alter table public.bookings add constraint bookings_renter_id_fkey FOREIGN KEY (renter_id) REFERENCES profiles(id);
alter table public.dispute_events add constraint dispute_events_dispute_id_fkey FOREIGN KEY (dispute_id) REFERENCES disputes(id) ON DELETE CASCADE;
alter table public.dispute_events add constraint dispute_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id);
alter table public.disputes add constraint disputes_raised_by_fkey FOREIGN KEY (raised_by) REFERENCES profiles(id);
alter table public.disputes add constraint disputes_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE;
alter table public.host_wallets add constraint host_wallets_host_id_fkey FOREIGN KEY (host_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.messages add constraint messages_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE;
alter table public.messages add constraint messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.notifications add constraint notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.notifications add constraint notifications_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE;
alter table public.parking_spaces add constraint parking_spaces_host_id_fkey FOREIGN KEY (host_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.payout_requests add constraint payout_requests_host_id_fkey FOREIGN KEY (host_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.profile_contacts add constraint profile_contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.reviews add constraint reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE;
alter table public.reviews add constraint reviews_reviewee_id_fkey FOREIGN KEY (reviewee_id) REFERENCES profiles(id);
alter table public.reviews add constraint reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES profiles(id);
alter table public.reviews add constraint reviews_space_id_fkey FOREIGN KEY (space_id) REFERENCES parking_spaces(id) ON DELETE SET NULL;
alter table public.subscriptions add constraint subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.user_roles add constraint user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wallet_transactions add constraint wallet_transactions_host_id_fkey FOREIGN KEY (host_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.wallet_transactions add constraint wallet_transactions_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL;
alter table public.messages add constraint messages_body_check CHECK (((length(body) >= 1) AND (length(body) <= 2000)));
alter table public.parking_spaces add constraint parking_spaces_cancellation_policy_check CHECK ((cancellation_policy = ANY (ARRAY['flexible'::text, 'moderate'::text, 'strict'::text])));
alter table public.payout_requests add constraint payout_requests_amount_check CHECK ((amount > (0)::numeric));
alter table public.reviews add constraint reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5)));

-- ============ INDEXES ============
CREATE INDEX idx_activity_user ON public.activity_log USING btree (user_id, created_at DESC);
CREATE INDEX idx_slots_space ON public.availability_slots USING btree (space_id, start_time);
CREATE INDEX idx_bookings_hold ON public.bookings USING btree (space_id, hold_expires_at) WHERE (status = 'pending'::text);
CREATE INDEX idx_bookings_host ON public.bookings USING btree (host_id);
CREATE INDEX idx_bookings_renter ON public.bookings USING btree (renter_id);
CREATE INDEX idx_bookings_space ON public.bookings USING btree (space_id);
CREATE INDEX idx_dispute_events_dispute ON public.dispute_events USING btree (dispute_id, created_at);
CREATE INDEX messages_booking_created_idx ON public.messages USING btree (booking_id, created_at);
CREATE INDEX notifications_user_created_idx ON public.notifications USING btree (user_id, created_at DESC);
CREATE INDEX idx_parking_host ON public.parking_spaces USING btree (host_id);
CREATE INDEX idx_parking_location ON public.parking_spaces USING gist (location);
CREATE INDEX payout_requests_host_idx ON public.payout_requests USING btree (host_id, created_at DESC);
CREATE INDEX idx_reviews_reviewee ON public.reviews USING btree (reviewee_id);
CREATE INDEX idx_reviews_space ON public.reviews USING btree (space_id);
CREATE UNIQUE INDEX reviews_booking_reviewer_unique ON public.reviews USING btree (booking_id, reviewer_id);
CREATE INDEX idx_subscriptions_user_id ON public.subscriptions USING btree (user_id);
CREATE INDEX wallet_transactions_host_idx ON public.wallet_transactions USING btree (host_id, created_at DESC);

-- ============ FUNCTIONS ============
CREATE OR REPLACE FUNCTION public.account_deletion_blockers()
 RETURNS TABLE(reason text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT 'You have an upcoming or in-progress reservation.'::text
  WHERE EXISTS (
    SELECT 1 FROM public.bookings b
    WHERE (b.renter_id = auth.uid() OR b.host_id = auth.uid())
      AND b.status IN ('confirmed','active') AND b.end_time > now())
  UNION ALL
  SELECT 'A refund on one of your bookings is still being processed.'
  WHERE EXISTS (
    SELECT 1 FROM public.bookings b
    WHERE b.renter_id = auth.uid() AND b.payment_status = 'refund_pending')
  UNION ALL
  SELECT 'You still have money in your host wallet. Withdraw it before deleting your account.'
  WHERE EXISTS (
    SELECT 1 FROM public.host_wallets w
    WHERE w.host_id = auth.uid() AND (w.available_balance > 0 OR w.pending_clearance > 0 OR w.pending_payout > 0))
  UNION ALL
  SELECT 'You have an active Host Pro subscription. Cancel it in the billing portal first.'
  WHERE EXISTS (
    SELECT 1 FROM public.subscriptions s
    WHERE s.user_id = auth.uid() AND s.status IN ('active','trialing','past_due'));
$function$
;

CREATE OR REPLACE FUNCTION public.admin_list_disputes()
 RETURNS TABLE(id uuid, booking_id uuid, raised_by uuid, reason text, status text, admin_notes text, created_at timestamp with time zone, renter_name text, host_name text, space_title text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT d.id, d.booking_id, d.raised_by, d.reason, d.status, d.admin_notes, d.created_at,
    rp.full_name, hp.full_name, s.title
  FROM public.disputes d
  JOIN public.bookings b ON b.id = d.booking_id
  LEFT JOIN public.profiles rp ON rp.id = b.renter_id
  LEFT JOIN public.profiles hp ON hp.id = b.host_id
  LEFT JOIN public.parking_spaces s ON s.id = b.space_id
  WHERE public.has_role(auth.uid(),'admin')
  ORDER BY d.created_at DESC;
$function$
;

CREATE OR REPLACE FUNCTION public.admin_list_payouts()
 RETURNS TABLE(id uuid, host_id uuid, host_name text, amount numeric, status text, account_holder text, account_number text, bank_code text, bank_name text, is_automatic boolean, admin_notes text, requested_at timestamp with time zone, processed_at timestamp with time zone)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::app_role) THEN RAISE EXCEPTION 'Forbidden'; END IF;
  RETURN QUERY
  SELECT p.id, p.host_id, pr.full_name, p.amount, p.status, p.account_holder, p.account_number,
         p.bank_code, p.bank_name, p.is_automatic, p.admin_notes, p.requested_at, p.processed_at
  FROM public.payout_requests p
  LEFT JOIN public.profiles pr ON pr.id = p.host_id
  ORDER BY (p.status = 'pending') DESC, p.created_at DESC;
END; $function$
;

CREATE OR REPLACE FUNCTION public.admin_process_payout(p_payout_id uuid, p_action text, p_notes text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE r public.payout_requests; v_bal numeric;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::app_role) THEN RAISE EXCEPTION 'Forbidden'; END IF;
  SELECT * INTO r FROM public.payout_requests WHERE id = p_payout_id FOR UPDATE;
  IF r.id IS NULL THEN RAISE EXCEPTION 'Payout not found'; END IF;
  IF r.status NOT IN ('pending','approved') THEN RAISE EXCEPTION 'Payout already finalised'; END IF;

  IF p_action = 'approve' THEN
    UPDATE public.payout_requests SET status = 'approved', admin_notes = COALESCE(p_notes, admin_notes) WHERE id = r.id;
  ELSIF p_action = 'paid' THEN
    UPDATE public.payout_requests SET status = 'paid', processed_at = now(), admin_notes = COALESCE(p_notes, admin_notes) WHERE id = r.id;
    UPDATE public.host_wallets
      SET pending_payout = GREATEST(0, pending_payout - r.amount),
          total_paid_out = total_paid_out + r.amount, updated_at = now()
      WHERE host_id = r.host_id RETURNING available_balance INTO v_bal;
    INSERT INTO public.wallet_transactions(host_id, payout_id, kind, amount, balance_after, note)
    VALUES (r.host_id, r.id, 'payout_paid', -r.amount, COALESCE(v_bal,0), 'Payout sent to bank account');
    INSERT INTO public.notifications(user_id, kind, title, body, link)
    VALUES (r.host_id, 'payment', 'Payout sent', 'Your payout of ' || to_char(r.amount,'FM999999990.00') || ' has been sent to your bank.', '/host/earnings');
  ELSIF p_action = 'reject' THEN
    UPDATE public.payout_requests SET status = 'rejected', processed_at = now(), admin_notes = COALESCE(p_notes, admin_notes) WHERE id = r.id;
    UPDATE public.host_wallets
      SET pending_payout = GREATEST(0, pending_payout - r.amount),
          available_balance = available_balance + r.amount, updated_at = now()
      WHERE host_id = r.host_id RETURNING available_balance INTO v_bal;
    INSERT INTO public.wallet_transactions(host_id, payout_id, kind, amount, balance_after, note)
    VALUES (r.host_id, r.id, 'payout_reverted', r.amount, COALESCE(v_bal,0), 'Payout rejected — amount returned to available balance');
    INSERT INTO public.notifications(user_id, kind, title, body, link)
    VALUES (r.host_id, 'payment', 'Payout rejected', COALESCE(p_notes, 'Your payout request was rejected and the funds returned to your balance.'), '/host/earnings');
  ELSE
    RAISE EXCEPTION 'Unknown action';
  END IF;
END; $function$
;

CREATE OR REPLACE FUNCTION public.admin_stats()
 RETURNS TABLE(users bigint, spaces bigint, active_spaces bigint, bookings bigint, completed_bookings bigint, total_revenue numeric, avg_trust_score numeric, open_disputes bigint)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    (SELECT count(*) FROM public.profiles),
    (SELECT count(*) FROM public.parking_spaces),
    (SELECT count(*) FROM public.parking_spaces WHERE is_active = true),
    (SELECT count(*) FROM public.bookings),
    (SELECT count(*) FROM public.bookings WHERE status = 'completed'),
    (SELECT coalesce(sum(total_price), 0) FROM public.bookings WHERE status = 'completed' AND payment_status = 'paid'),
    (SELECT coalesce(round(avg(trust_score)::numeric, 1), 0) FROM public.profiles),
    (SELECT count(*) FROM public.disputes WHERE status = 'open')
  WHERE public.has_role(auth.uid(),'admin');
$function$
;

CREATE OR REPLACE FUNCTION public.admin_top_demand_areas(p_limit integer DEFAULT 5)
 RETURNS TABLE(address text, bookings bigint, revenue numeric, active_listings bigint)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    ps.address,
    count(b.id) AS bookings,
    coalesce(sum(b.total_price) FILTER (WHERE b.status = 'completed' AND b.payment_status = 'paid'), 0) AS revenue,
    count(DISTINCT ps.id) FILTER (WHERE ps.is_active) AS active_listings
  FROM public.parking_spaces ps
  LEFT JOIN public.bookings b ON b.space_id = ps.id
  WHERE public.has_role(auth.uid(), 'admin')
  GROUP BY ps.address
  ORDER BY bookings DESC, revenue DESC
  LIMIT greatest(p_limit, 1);
$function$
;

CREATE OR REPLACE FUNCTION public.cancel_booking(p_booking_id uuid, p_reason text DEFAULT NULL::text)
 RETURNS bookings
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_booking public.bookings;
  v_role text;
  v_policy text;
  v_cut integer;
  v_hours numeric;
  v_refund numeric := 0;
  v_bal numeric;
  v_space text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_booking FROM public.bookings WHERE id = p_booking_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Booking not found' USING ERRCODE = 'P0002';
  END IF;

  IF v_booking.renter_id = auth.uid() THEN
    v_role := 'renter';
  ELSIF v_booking.host_id = auth.uid() THEN
    v_role := 'host';
  ELSE
    RAISE EXCEPTION 'Only the renter or host can cancel this booking' USING ERRCODE = '42501';
  END IF;

  IF v_booking.status = 'cancelled' THEN
    RAISE EXCEPTION 'Booking is already cancelled' USING ERRCODE = '22023';
  END IF;
  IF v_booking.status NOT IN ('pending', 'confirmed') THEN
    RAISE EXCEPTION 'Booking cannot be cancelled from status %', v_booking.status USING ERRCODE = '22023';
  END IF;
  IF v_booking.checked_in_at IS NOT NULL THEN
    RAISE EXCEPTION 'Booking already checked in and cannot be cancelled' USING ERRCODE = '22023';
  END IF;

  SELECT s.cancellation_policy, s.title INTO v_policy, v_space
    FROM public.parking_spaces s WHERE s.id = v_booking.space_id;
  v_policy := COALESCE(v_policy, 'moderate');
  v_cut := public.cancellation_cutoff_hours(v_policy);
  v_hours := EXTRACT(epoch FROM (v_booking.start_time - now())) / 3600.0;

  IF v_booking.payment_status = 'paid'
     AND (v_role = 'host' OR v_hours >= v_cut) THEN
    v_refund := round(v_booking.amount_charged, 2);
  END IF;

  UPDATE public.bookings
  SET status = 'cancelled',
      cancelled_at = now(),
      cancelled_by = auth.uid(),
      cancellation_reason = p_reason,
      refund_amount = v_refund,
      payment_status = CASE WHEN v_refund > 0 THEN 'refund_pending' ELSE payment_status END,
      updated_at = now()
  WHERE id = p_booking_id
  RETURNING * INTO v_booking;

  -- Reverse the host's credit when a refund is owed
  IF v_refund > 0 AND v_booking.host_earning > 0 THEN
    IF v_booking.earnings_released_at IS NULL THEN
      UPDATE public.host_wallets SET
        pending_clearance = GREATEST(0, pending_clearance - v_booking.host_earning),
        updated_at = now()
      WHERE host_id = v_booking.host_id
      RETURNING available_balance INTO v_bal;
    ELSE
      UPDATE public.host_wallets SET
        available_balance = GREATEST(0, available_balance - v_booking.host_earning),
        lifetime_earnings = GREATEST(0, lifetime_earnings - v_booking.host_earning),
        updated_at = now()
      WHERE host_id = v_booking.host_id
      RETURNING available_balance INTO v_bal;
    END IF;

    INSERT INTO public.wallet_transactions(host_id, booking_id, kind, amount, balance_after, note)
    VALUES (v_booking.host_id, v_booking.id, 'refund_reversal', -v_booking.host_earning, COALESCE(v_bal,0),
      'Booking cancelled — earnings reversed for refund');
  END IF;

  INSERT INTO public.notifications(user_id, kind, title, body, link, booking_id) VALUES
    (v_booking.renter_id, 'info',
      CASE WHEN v_refund > 0 THEN 'Booking cancelled — refund on the way' ELSE 'Booking cancelled' END,
      CASE WHEN v_refund > 0
        THEN 'Your refund of ' || to_char(v_refund,'FM999999990.00') || ' is being processed.'
        ELSE 'This booking was cancelled. The ' || v_policy || ' policy cutoff (' || v_cut || 'h before start) had passed, so no refund applies.' END,
      '/bookings', v_booking.id),
    (v_booking.host_id, 'info', 'Booking cancelled',
      'A booking for ' || COALESCE(v_space,'your space') || ' was cancelled by the ' || v_role || '.',
      '/host', v_booking.id);

  INSERT INTO public.activity_log (user_id, action, reference_id, metadata)
  VALUES (auth.uid(), 'booking_cancelled', p_booking_id,
          jsonb_build_object('role', v_role, 'reason', p_reason, 'policy', v_policy, 'refund', v_refund));

  RETURN v_booking;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.cancellation_cutoff_hours(_policy text)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$ SELECT CASE _policy WHEN 'flexible' THEN 1 WHEN 'strict' THEN 24 ELSE 12 END; $function$
;

CREATE OR REPLACE FUNCTION public.checkin_booking(p_qr_code text)
 RETURNS TABLE(booking_id uuid, space_title text, renter_name text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_b record;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

  SELECT b.id, b.space_id, b.host_id, b.renter_id, b.status, s.title
    INTO v_b
  FROM public.bookings b
  JOIN public.parking_spaces s ON s.id = b.space_id
  WHERE b.qr_checkin_code = p_qr_code
  LIMIT 1;

  IF v_b.id IS NULL THEN RAISE EXCEPTION 'Invalid check-in code'; END IF;
  IF v_b.host_id <> v_uid THEN RAISE EXCEPTION 'Only the host can check in this booking'; END IF;
  IF v_b.status = 'active' THEN RAISE EXCEPTION 'Already checked in'; END IF;
  IF v_b.status NOT IN ('pending','confirmed') THEN RAISE EXCEPTION 'Booking is %', v_b.status; END IF;

  UPDATE public.bookings
     SET status = 'active', checked_in_at = now(), updated_at = now()
   WHERE id = v_b.id;

  UPDATE public.parking_spaces
     SET live_occupancy_status = 'occupied', updated_at = now()
   WHERE id = v_b.space_id;

  RETURN QUERY
  SELECT v_b.id, v_b.title,
         COALESCE((SELECT full_name FROM public.profiles WHERE id = v_b.renter_id), 'Renter');
END;
$function$
;

CREATE OR REPLACE FUNCTION public.checkout_booking(p_booking_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_b record;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

  SELECT * INTO v_b FROM public.bookings WHERE id = p_booking_id;
  IF v_b.id IS NULL THEN RAISE EXCEPTION 'Booking not found'; END IF;
  IF v_uid <> v_b.host_id AND v_uid <> v_b.renter_id THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;
  IF v_b.status <> 'active' THEN RAISE EXCEPTION 'Booking is % (must be active)', v_b.status; END IF;

  UPDATE public.bookings
     SET status = 'completed', checked_out_at = now(), updated_at = now()
   WHERE id = p_booking_id;

  UPDATE public.parking_spaces
     SET live_occupancy_status = 'available', updated_at = now()
   WHERE id = v_b.space_id;

  UPDATE public.profiles SET total_bookings = total_bookings + 1 WHERE id = v_b.host_id;
  UPDATE public.profiles SET total_bookings = total_bookings + 1 WHERE id = v_b.renter_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_parking_space(p_title text, p_description text, p_address text, p_lat double precision, p_lng double precision, p_price_per_hour numeric, p_price_per_day numeric, p_vehicle_types text[], p_is_covered boolean, p_is_gated boolean, p_has_ev_charging boolean, p_has_camera boolean, p_has_sensor boolean, p_photos text[], p_cancellation_policy text DEFAULT 'moderate'::text, p_env text DEFAULT 'live'::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE new_id uuid; v_count integer;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF COALESCE(p_cancellation_policy,'moderate') NOT IN ('flexible','moderate','strict') THEN
    RAISE EXCEPTION 'Invalid cancellation policy';
  END IF;
  IF NOT public.is_host_pro(auth.uid(), p_env) THEN
    SELECT count(*) INTO v_count FROM public.parking_spaces WHERE host_id = auth.uid();
    IF v_count >= 2 THEN
      RAISE EXCEPTION 'Free hosts can list up to 2 spaces. Upgrade to Host Pro for unlimited listings.'
        USING ERRCODE = '42501';
    END IF;
  END IF;

  INSERT INTO public.parking_spaces (
    host_id, title, description, address, location, price_per_hour, price_per_day, vehicle_types,
    is_covered, is_gated, has_ev_charging, has_camera, has_sensor, photos, is_active, cancellation_policy
  ) VALUES (
    auth.uid(), p_title, p_description, p_address,
    ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326)::geography,
    p_price_per_hour, p_price_per_day, p_vehicle_types,
    p_is_covered, p_is_gated, p_has_ev_charging, p_has_camera, p_has_sensor,
    COALESCE(p_photos, ARRAY[]::text[]), true, COALESCE(p_cancellation_policy,'moderate')
  ) RETURNING id INTO new_id;
  RETURN new_id;
END; $function$
;

CREATE OR REPLACE FUNCTION public.create_pending_booking(p_space_id uuid, p_start timestamp with time zone, p_end timestamp with time zone)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_hours numeric; v_price_per_hour numeric; v_host_id uuid; v_total numeric; v_booking_id uuid;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF p_end <= p_start THEN RAISE EXCEPTION 'End must be after start'; END IF;

  SELECT s.price_per_hour, s.host_id INTO v_price_per_hour, v_host_id
  FROM public.parking_spaces s WHERE s.id = p_space_id AND s.is_active = true;

  IF v_host_id IS NULL THEN RAISE EXCEPTION 'Space not found or inactive'; END IF;
  IF v_host_id = v_uid THEN RAISE EXCEPTION 'Cannot book your own space'; END IF;

  IF EXISTS (
    SELECT 1 FROM public.bookings b
    WHERE b.space_id = p_space_id
      AND (
        b.status IN ('confirmed','active')
        OR (b.status = 'pending' AND b.payment_status <> 'paid'
            AND b.hold_expires_at IS NOT NULL AND b.hold_expires_at > now()
            AND b.renter_id <> v_uid)
      )
      AND tstzrange(b.start_time, b.end_time, '[)') && tstzrange(p_start, p_end, '[)')
  ) THEN
    RAISE EXCEPTION 'Time slot no longer available';
  END IF;

  v_hours := EXTRACT(EPOCH FROM (p_end - p_start)) / 3600.0;
  v_total := ROUND(v_hours * v_price_per_hour, 2);

  INSERT INTO public.bookings (
    space_id, renter_id, host_id, start_time, end_time, total_price,
    status, payment_status, qr_checkin_code, hold_expires_at
  ) VALUES (
    p_space_id, v_uid, v_host_id, p_start, p_end, v_total,
    'pending', 'pending', encode(gen_random_bytes(8), 'hex'), now() + interval '15 minutes'
  ) RETURNING id INTO v_booking_id;

  RETURN v_booking_id;
END; $function$
;

CREATE OR REPLACE FUNCTION public.expire_pending_bookings()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_n integer;
BEGIN
  WITH expired AS (
    UPDATE public.bookings
    SET status = 'cancelled', cancelled_at = now(),
        cancellation_reason = 'Checkout not completed in time', updated_at = now()
    WHERE status = 'pending' AND payment_status <> 'paid'
      AND hold_expires_at IS NOT NULL AND hold_expires_at < now() - interval '5 minutes'
    RETURNING id
  )
  SELECT count(*) INTO v_n FROM expired;
  RETURN v_n;
END; $function$
;

CREATE OR REPLACE FUNCTION public.get_booking_charge(p_booking_id uuid, p_env text DEFAULT 'live'::text)
 RETURNS TABLE(base_amount numeric, platform_fee numeric, reservation_fee numeric, total numeric, credits integer)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE b public.bookings; v_base numeric; v_fee numeric; v_res numeric := 1; v_rate numeric;
        v_credits integer;
BEGIN
  SELECT * INTO b FROM public.bookings WHERE id = p_booking_id;
  IF b.id IS NULL THEN RAISE EXCEPTION 'Booking not found'; END IF;
  IF b.renter_id <> auth.uid() THEN RAISE EXCEPTION 'Not your booking'; END IF;
  v_base := round(b.total_price::numeric, 2);
  v_rate := public.host_commission_rate(b.host_id, p_env);
  v_fee := round(v_base * v_rate, 2);
  IF v_base + v_fee > 500 THEN
    RAISE EXCEPTION 'Bookings above $500 cannot be paid online yet. Please shorten the reservation.';
  END IF;
  -- Parking is sold in whole $1 credits, so the quote is rounded up to match
  -- exactly what the checkout will charge.
  v_credits := GREATEST(1, ceil(v_base + v_fee)::integer);
  RETURN QUERY SELECT v_base, v_fee, v_res, (v_credits + v_res)::numeric, v_credits;
END; $function$
;

CREATE OR REPLACE FUNCTION public.get_cancellation_quote(p_booking_id uuid)
 RETURNS TABLE(policy text, cutoff_hours integer, hours_until_start numeric, refundable boolean, refund_amount numeric)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE b public.bookings; v_policy text; v_cut integer; v_hours numeric; v_ok boolean;
BEGIN
  SELECT * INTO b FROM public.bookings WHERE id = p_booking_id;
  IF b.id IS NULL THEN RAISE EXCEPTION 'Booking not found'; END IF;
  IF auth.uid() NOT IN (b.renter_id, b.host_id) THEN RAISE EXCEPTION 'Not your booking'; END IF;

  SELECT s.cancellation_policy INTO v_policy FROM public.parking_spaces s WHERE s.id = b.space_id;
  v_policy := COALESCE(v_policy, 'moderate');
  v_cut := public.cancellation_cutoff_hours(v_policy);
  v_hours := round(EXTRACT(epoch FROM (b.start_time - now())) / 3600.0, 2);
  v_ok := (b.payment_status = 'paid') AND (auth.uid() = b.host_id OR v_hours >= v_cut);

  RETURN QUERY SELECT v_policy, v_cut, v_hours, v_ok,
    CASE WHEN v_ok THEN round(b.amount_charged, 2) ELSE 0::numeric END;
END; $function$
;

CREATE OR REPLACE FUNCTION public.get_my_wallet()
 RETURNS TABLE(lifetime_earnings numeric, available_balance numeric, pending_clearance numeric, pending_payout numeric, total_paid_out numeric)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT COALESCE(w.lifetime_earnings,0), COALESCE(w.available_balance,0),
         COALESCE(w.pending_clearance,0), COALESCE(w.pending_payout,0), COALESCE(w.total_paid_out,0)
  FROM (SELECT auth.uid() AS uid) u
  LEFT JOIN public.host_wallets w ON w.host_id = u.uid;
$function$
;

CREATE OR REPLACE FUNCTION public.get_refund_job(p_booking_id uuid)
 RETURNS TABLE(transaction_id text, refund_amount numeric, payment_status text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT paddle_transaction_id, refund_amount, payment_status
  FROM public.bookings WHERE id = p_booking_id;
$function$
;

CREATE OR REPLACE FUNCTION public.get_space_detail(p_id uuid)
 RETURNS TABLE(id uuid, title text, description text, address text, lat double precision, lng double precision, price_per_hour numeric, price_per_day numeric, photos text[], is_covered boolean, is_gated boolean, has_ev_charging boolean, has_camera boolean, has_sensor boolean, vehicle_types text[], live_occupancy_status text, host_id uuid, host_name text, host_rating numeric, host_trust_score integer, cancellation_policy text, is_featured boolean)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    s.id, s.title, s.description, s.address,
    ST_Y(s.location::geometry), ST_X(s.location::geometry),
    s.price_per_hour, s.price_per_day, s.photos,
    s.is_covered, s.is_gated, s.has_ev_charging, s.has_camera, s.has_sensor,
    s.vehicle_types, s.live_occupancy_status,
    p.id, p.full_name, p.rating, p.trust_score,
    s.cancellation_policy,
    public.is_host_pro(s.host_id)
  FROM public.parking_spaces s
  JOIN public.profiles p ON p.id = s.host_id
  WHERE s.id = p_id AND s.is_active = true;
$function$
;

CREATE OR REPLACE FUNCTION public.grant_role(p_user_id uuid, p_role app_role)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT public.has_role(auth.uid(),'admin') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  INSERT INTO public.user_roles(user_id, role) VALUES (p_user_id, p_role)
    ON CONFLICT DO NOTHING;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', ''),
    COALESCE(NEW.raw_user_meta_data->>'avatar_url', NEW.raw_user_meta_data->>'picture', '')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.has_active_subscription(user_uuid uuid, check_env text DEFAULT 'live'::text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.subscriptions
    WHERE user_id = user_uuid AND environment = check_env
      AND ((status IN ('active','trialing') AND (current_period_end IS NULL OR current_period_end > now()))
        OR (status = 'canceled' AND current_period_end > now()))
  );
$function$
;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role app_role)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role);
$function$
;

CREATE OR REPLACE FUNCTION public.host_commission_rate(_host_id uuid, _env text DEFAULT 'live'::text)
 RETURNS numeric
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT CASE WHEN public.is_host_pro(_host_id, _env) THEN 0.05 ELSE 0.10 END;
$function$
;

CREATE OR REPLACE FUNCTION public.host_earnings_analytics(p_env text DEFAULT 'live'::text)
 RETURNS TABLE(month date, bookings bigint, gross numeric, net numeric)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Not authenticated' USING ERRCODE='28000'; END IF;
  IF NOT public.is_host_pro(auth.uid(), p_env) THEN
    RAISE EXCEPTION 'Host Pro required' USING ERRCODE='42501';
  END IF;
  RETURN QUERY
    SELECT date_trunc('month', b.start_time)::date, count(*)::bigint,
           round(sum(b.total_price),2), round(sum(b.host_earning),2)
    FROM public.bookings b
    WHERE b.host_id = auth.uid()
      AND b.payment_status IN ('paid','refunded','refund_pending')
      AND b.start_time > now() - interval '12 months'
    GROUP BY 1 ORDER BY 1;
END; $function$
;

CREATE OR REPLACE FUNCTION public.is_booking_party(_booking_id uuid, _user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.bookings b
    JOIN public.parking_spaces s ON s.id = b.space_id
    WHERE b.id = _booking_id AND (b.renter_id = _user_id OR s.host_id = _user_id)
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_host_pro(_user_id uuid, _env text DEFAULT 'live'::text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.subscriptions s
    WHERE s.user_id = _user_id
      AND s.environment = COALESCE(_env, 'live')
      AND (
        (s.status IN ('active','trialing','past_due')
          AND (s.current_period_end IS NULL OR s.current_period_end > now()))
        OR (s.status = 'canceled' AND s.current_period_end > now())
      )
  );
$function$
;

CREATE OR REPLACE FUNCTION public.list_dispute_events(p_dispute_id uuid)
 RETURNS TABLE(id uuid, actor_id uuid, actor_name text, from_status text, to_status text, note text, created_at timestamp with time zone)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  SELECT e.id, e.actor_id, p.full_name, e.from_status, e.to_status, e.note, e.created_at
  FROM public.dispute_events e
  LEFT JOIN public.profiles p ON p.id = e.actor_id
  WHERE e.dispute_id = p_dispute_id
  ORDER BY e.created_at ASC;
$function$
;

CREATE OR REPLACE FUNCTION public.list_my_payouts()
 RETURNS TABLE(id uuid, amount numeric, status text, bank_name text, account_number text, is_automatic boolean, admin_notes text, requested_at timestamp with time zone, processed_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT p.id, p.amount, p.status, p.bank_name,
         CASE WHEN p.account_number IS NULL THEN NULL
              ELSE repeat('•', GREATEST(0, length(p.account_number) - 4)) || right(p.account_number, 4) END,
         p.is_automatic, p.admin_notes, p.requested_at, p.processed_at
  FROM public.payout_requests p
  WHERE p.host_id = auth.uid()
  ORDER BY p.created_at DESC;
$function$
;

CREATE OR REPLACE FUNCTION public.list_my_spaces()
 RETURNS TABLE(id uuid, title text, address text, lat double precision, lng double precision, price_per_hour numeric, price_per_day numeric, is_active boolean, live_occupancy_status text, photos text[], created_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT id, title, address,
    ST_Y(location::geometry) AS lat,
    ST_X(location::geometry) AS lng,
    price_per_hour, price_per_day, is_active, live_occupancy_status, photos, created_at
  FROM public.parking_spaces
  WHERE host_id = auth.uid()
  ORDER BY created_at DESC;
$function$
;

CREATE OR REPLACE FUNCTION public.list_my_wallet_transactions(p_limit integer DEFAULT 50)
 RETURNS TABLE(id uuid, kind text, amount numeric, balance_after numeric, note text, created_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT t.id, t.kind, t.amount, t.balance_after, t.note, t.created_at
  FROM public.wallet_transactions t
  WHERE t.host_id = auth.uid()
  ORDER BY t.created_at DESC
  LIMIT LEAST(COALESCE(p_limit,50), 200);
$function$
;

CREATE OR REPLACE FUNCTION public.log_booking_activity()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.activity_log(user_id, action, reference_id, metadata)
      VALUES (NEW.renter_id, 'booking_created', NEW.id,
        jsonb_build_object('space_id', NEW.space_id, 'total_price', NEW.total_price));
    INSERT INTO public.activity_log(user_id, action, reference_id, metadata)
      VALUES (NEW.host_id, 'booking_received', NEW.id,
        jsonb_build_object('space_id', NEW.space_id, 'renter_id', NEW.renter_id));
  ELSIF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status THEN
    INSERT INTO public.activity_log(user_id, action, reference_id, metadata)
      VALUES (NEW.renter_id, 'booking_' || NEW.status, NEW.id, jsonb_build_object('space_id', NEW.space_id));
    INSERT INTO public.activity_log(user_id, action, reference_id, metadata)
      VALUES (NEW.host_id, 'booking_' || NEW.status, NEW.id, jsonb_build_object('space_id', NEW.space_id));
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.log_dispute_event()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.dispute_events(dispute_id, actor_id, from_status, to_status, note)
    VALUES (NEW.id, NEW.raised_by, NULL, NEW.status, NEW.reason);
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' AND (
    NEW.status IS DISTINCT FROM OLD.status
    OR NEW.admin_notes IS DISTINCT FROM OLD.admin_notes
  ) THEN
    INSERT INTO public.dispute_events(dispute_id, actor_id, from_status, to_status, note)
    VALUES (NEW.id, auth.uid(), OLD.status, NEW.status, NEW.admin_notes);
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.log_review_activity()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.activity_log(user_id, action, reference_id, metadata)
    VALUES (NEW.reviewer_id, 'review_left', NEW.booking_id,
      jsonb_build_object('rating', NEW.rating, 'space_id', NEW.space_id));
  INSERT INTO public.activity_log(user_id, action, reference_id, metadata)
    VALUES (NEW.reviewee_id, 'review_received', NEW.booking_id,
      jsonb_build_object('rating', NEW.rating));
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.mark_booking_refunded(p_booking_id uuid, p_refund_id text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE b public.bookings;
BEGIN
  UPDATE public.bookings
  SET payment_status = 'refunded',
      paddle_refund_id = COALESCE(p_refund_id, paddle_refund_id),
      updated_at = now()
  WHERE id = p_booking_id AND payment_status <> 'refunded'
  RETURNING * INTO b;

  IF b.id IS NULL THEN RETURN; END IF;

  INSERT INTO public.notifications(user_id, kind, title, body, link, booking_id)
  VALUES (b.renter_id, 'payment', 'Refund issued',
    to_char(GREATEST(b.refund_amount, 0),'FM999999990.00') || ' has been refunded to your original payment method.',
    '/bookings', b.id);
END; $function$
;

CREATE OR REPLACE FUNCTION public.mark_booking_refunded_by_transaction(p_transaction_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_id uuid;
BEGIN
  SELECT id INTO v_id FROM public.bookings WHERE paddle_transaction_id = p_transaction_id LIMIT 1;
  IF v_id IS NOT NULL THEN PERFORM public.mark_booking_refunded(v_id, NULL); END IF;
END; $function$
;

CREATE OR REPLACE FUNCTION public.mark_notifications_read()
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  UPDATE public.notifications SET read_at = now()
  WHERE user_id = auth.uid() AND read_at IS NULL;
$function$
;

CREATE OR REPLACE FUNCTION public.my_billing_history(p_env text DEFAULT 'live'::text)
 RETURNS TABLE(kind text, description text, amount numeric, status text, reference text, occurred_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT 'booking'::text,
         'Parking at ' || COALESCE(s.title, 'a space'),
         CASE WHEN b.payment_status = 'refunded' THEN -COALESCE(b.refund_amount,0) ELSE b.amount_charged END,
         b.payment_status, b.paddle_transaction_id, b.updated_at
  FROM public.bookings b
  LEFT JOIN public.parking_spaces s ON s.id = b.space_id
  WHERE b.renter_id = auth.uid() AND b.payment_status IN ('paid','refunded','refund_pending')
  UNION ALL
  SELECT 'subscription'::text,
         'Host Pro (' || sub.price_id || ')',
         NULL::numeric, sub.status, sub.paddle_subscription_id, COALESCE(sub.updated_at, sub.created_at)
  FROM public.subscriptions sub
  WHERE sub.user_id = auth.uid() AND sub.environment = COALESCE(p_env,'live')
  ORDER BY 6 DESC
  LIMIT 100;
$function$
;

CREATE OR REPLACE FUNCTION public.my_listing_quota(p_env text DEFAULT 'live'::text)
 RETURNS TABLE(used integer, max_allowed integer, is_pro boolean)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    (SELECT count(*)::integer FROM public.parking_spaces WHERE host_id = auth.uid()),
    CASE WHEN public.is_host_pro(auth.uid(), p_env) THEN 2147483647 ELSE 2 END,
    public.is_host_pro(auth.uid(), p_env);
$function$
;

CREATE OR REPLACE FUNCTION public.nearby_spaces(lat double precision, lng double precision, radius_km double precision)
 RETURNS SETOF parking_spaces
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  SELECT *
  FROM public.parking_spaces
  WHERE is_active = true
    AND location IS NOT NULL
    AND ST_DWithin(
      location,
      ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography,
      radius_km * 1000
    )
  ORDER BY location <-> ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_on_booking()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_host uuid;
BEGIN
  SELECT host_id INTO v_host FROM public.parking_spaces WHERE id = NEW.space_id;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.notifications (user_id, kind, title, body, link, booking_id)
    VALUES (v_host, 'booking_new', 'New booking request',
            'A renter reserved your space.', '/host', NEW.id);
  ELSIF TG_OP = 'UPDATE' AND NEW.status <> OLD.status THEN
    INSERT INTO public.notifications (user_id, kind, title, body, link, booking_id)
    VALUES (NEW.renter_id, 'booking_status',
            'Booking ' || NEW.status,
            'Your booking is now ' || NEW.status || '.',
            '/bookings', NEW.id);
  END IF;
  RETURN NEW;
END; $function$
;

CREATE OR REPLACE FUNCTION public.notify_on_message()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_host uuid; v_renter uuid; v_recipient uuid; v_title text;
BEGIN
  SELECT b.renter_id, s.host_id INTO v_renter, v_host
  FROM public.bookings b JOIN public.parking_spaces s ON s.id = b.space_id
  WHERE b.id = NEW.booking_id;
  v_recipient := CASE WHEN NEW.sender_id = v_renter THEN v_host ELSE v_renter END;
  INSERT INTO public.notifications (user_id, kind, title, body, link, booking_id)
  VALUES (v_recipient, 'message', 'New message',
          left(NEW.body, 140),
          '/messages/' || NEW.booking_id::text,
          NEW.booking_id);
  RETURN NEW;
END; $function$
;

CREATE OR REPLACE FUNCTION public.raise_dispute(p_booking_id uuid, p_reason text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_caller uuid := auth.uid();
  v_dispute_id uuid;
  v_booking record;
BEGIN
  IF v_caller IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF length(coalesce(p_reason,'')) < 5 THEN RAISE EXCEPTION 'Reason too short'; END IF;

  SELECT id, renter_id, host_id INTO v_booking FROM public.bookings WHERE id = p_booking_id;
  IF v_booking.id IS NULL THEN RAISE EXCEPTION 'Booking not found'; END IF;
  IF v_caller NOT IN (v_booking.renter_id, v_booking.host_id) THEN
    RAISE EXCEPTION 'Not authorised';
  END IF;

  INSERT INTO public.disputes(booking_id, raised_by, reason, status)
    VALUES (p_booking_id, v_caller, p_reason, 'open')
    RETURNING id INTO v_dispute_id;

  INSERT INTO public.activity_log(user_id, action, reference_id, metadata)
    VALUES (v_caller, 'dispute_raised', v_dispute_id,
      jsonb_build_object('booking_id', p_booking_id, 'reason', p_reason));

  RETURN v_dispute_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.release_cleared_earnings()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE b record; v_bal numeric; v_n integer := 0;
BEGIN
  FOR b IN
    SELECT * FROM public.bookings
    WHERE payment_status = 'paid'
      AND status <> 'cancelled'
      AND host_earning > 0
      AND earnings_released_at IS NULL
      AND earnings_clear_at IS NOT NULL
      AND earnings_clear_at <= now()
      AND NOT EXISTS (
        SELECT 1 FROM public.disputes d
        WHERE d.booking_id = bookings.id AND d.status IN ('open','under_review')
      )
    FOR UPDATE
  LOOP
    UPDATE public.host_wallets SET
      pending_clearance = GREATEST(0, pending_clearance - b.host_earning),
      available_balance = available_balance + b.host_earning,
      lifetime_earnings = lifetime_earnings + b.host_earning,
      updated_at = now()
    WHERE host_id = b.host_id
    RETURNING available_balance INTO v_bal;

    UPDATE public.bookings SET earnings_released_at = now(), updated_at = now() WHERE id = b.id;

    INSERT INTO public.wallet_transactions(host_id, booking_id, kind, amount, balance_after, note)
    VALUES (b.host_id, b.id, 'earning_cleared', b.host_earning, COALESCE(v_bal,0),
      'Earnings cleared and available to withdraw');

    INSERT INTO public.notifications(user_id, kind, title, body, link, booking_id)
    VALUES (b.host_id, 'payment', 'Earnings cleared',
      to_char(b.host_earning,'FM999999990.00') || ' is now available to withdraw.', '/host/earnings', b.id);

    v_n := v_n + 1;
  END LOOP;
  RETURN v_n;
END; $function$
;

CREATE OR REPLACE FUNCTION public.request_payout(p_amount numeric, p_account_holder text, p_account_number text, p_bank_code text, p_bank_name text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_uid uuid := auth.uid(); v_bal numeric; v_id uuid;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF p_amount IS NULL OR p_amount < 20 THEN RAISE EXCEPTION 'Minimum payout amount is 20'; END IF;
  IF coalesce(trim(p_account_holder),'') = '' OR coalesce(trim(p_account_number),'') = '' THEN
    RAISE EXCEPTION 'Bank account details are required';
  END IF;

  SELECT available_balance INTO v_bal FROM public.host_wallets WHERE host_id = v_uid FOR UPDATE;
  IF v_bal IS NULL OR v_bal < p_amount THEN RAISE EXCEPTION 'Insufficient available balance'; END IF;

  INSERT INTO public.payout_requests(host_id, amount, account_holder, account_number, bank_code, bank_name)
  VALUES (v_uid, round(p_amount,2), trim(p_account_holder), trim(p_account_number), nullif(trim(p_bank_code),''), nullif(trim(p_bank_name),''))
  RETURNING id INTO v_id;

  UPDATE public.host_wallets
  SET available_balance = available_balance - round(p_amount,2),
      pending_payout = pending_payout + round(p_amount,2), updated_at = now()
  WHERE host_id = v_uid RETURNING available_balance INTO v_bal;

  INSERT INTO public.wallet_transactions(host_id, payout_id, kind, amount, balance_after, note)
  VALUES (v_uid, v_id, 'payout_hold', -round(p_amount,2), v_bal, 'Payout requested — awaiting admin approval');

  RETURN v_id;
END; $function$
;

CREATE OR REPLACE FUNCTION public.reset_demo_data()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_spaces uuid[];
  v_bookings uuid[];
  v_removed int := 0;
  v_bookings_removed int := 0;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.has_role(v_uid, 'admin'::app_role) THEN
    RAISE EXCEPTION 'Admins only';
  END IF;

  SELECT coalesce(array_agg(id), '{}') INTO v_spaces
  FROM public.parking_spaces
  WHERE host_id = v_uid AND title LIKE '[demo]%';

  IF array_length(v_spaces, 1) IS NULL THEN
    RETURN jsonb_build_object('spaces_removed', 0, 'bookings_removed', 0);
  END IF;

  SELECT coalesce(array_agg(id), '{}') INTO v_bookings
  FROM public.bookings WHERE space_id = ANY(v_spaces);

  DELETE FROM public.messages WHERE booking_id = ANY(v_bookings);
  DELETE FROM public.dispute_events WHERE dispute_id IN (
    SELECT id FROM public.disputes WHERE booking_id = ANY(v_bookings)
  );
  DELETE FROM public.disputes WHERE booking_id = ANY(v_bookings);
  DELETE FROM public.notifications WHERE booking_id = ANY(v_bookings);
  DELETE FROM public.reviews WHERE booking_id = ANY(v_bookings) OR space_id = ANY(v_spaces);
  DELETE FROM public.wallet_transactions WHERE booking_id = ANY(v_bookings);
  DELETE FROM public.availability_slots WHERE space_id = ANY(v_spaces);

  WITH del AS (DELETE FROM public.bookings WHERE space_id = ANY(v_spaces) RETURNING 1)
  SELECT count(*) INTO v_bookings_removed FROM del;

  WITH del AS (DELETE FROM public.parking_spaces WHERE id = ANY(v_spaces) RETURNING 1)
  SELECT count(*) INTO v_removed FROM del;

  RETURN jsonb_build_object('spaces_removed', v_removed, 'bookings_removed', v_bookings_removed);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.resolve_dispute(p_dispute_id uuid, p_status text, p_notes text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_caller uuid := auth.uid();
BEGIN
  IF NOT public.has_role(v_caller, 'admin') THEN RAISE EXCEPTION 'Admin only'; END IF;
  IF p_status NOT IN ('open','under_review','resolved','rejected') THEN RAISE EXCEPTION 'Bad status'; END IF;
  UPDATE public.disputes SET status = p_status, admin_notes = coalesce(p_notes, admin_notes), updated_at = now()
    WHERE id = p_dispute_id;
  INSERT INTO public.activity_log(user_id, action, reference_id, metadata)
    VALUES (v_caller, 'dispute_' || p_status, p_dispute_id, jsonb_build_object('notes', p_notes));
  -- Notify the party who raised the dispute
  INSERT INTO public.notifications(user_id, kind, title, body, link, booking_id)
  SELECT d.raised_by, 'dispute_' || p_status,
         'Dispute ' || replace(p_status,'_',' '),
         coalesce(p_notes, 'An admin updated your dispute.'),
         '/bookings', d.booking_id
  FROM public.disputes d WHERE d.id = p_dispute_id;
END; $function$
;

CREATE OR REPLACE FUNCTION public.run_monthly_payouts()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE w record; v_id uuid; v_bal numeric; v_count integer := 0; v_last record;
BEGIN
  FOR w IN SELECT * FROM public.host_wallets WHERE available_balance >= 20 LOOP
    SELECT * INTO v_last FROM public.payout_requests
      WHERE host_id = w.host_id AND account_number IS NOT NULL
      ORDER BY created_at DESC LIMIT 1;

    INSERT INTO public.payout_requests(host_id, amount, is_automatic, account_holder, account_number, bank_code, bank_name)
    VALUES (w.host_id, w.available_balance, true, v_last.account_holder, v_last.account_number, v_last.bank_code, v_last.bank_name)
    RETURNING id INTO v_id;

    UPDATE public.host_wallets
      SET pending_payout = pending_payout + w.available_balance,
          available_balance = 0, updated_at = now()
      WHERE host_id = w.host_id RETURNING available_balance INTO v_bal;

    INSERT INTO public.wallet_transactions(host_id, payout_id, kind, amount, balance_after, note)
    VALUES (w.host_id, v_id, 'payout_hold', -w.available_balance, v_bal, 'Automatic monthly payout scheduled');

    INSERT INTO public.notifications(user_id, kind, title, body, link)
    VALUES (w.host_id, 'payment', 'Monthly payout scheduled',
      'Your balance of ' || to_char(w.available_balance,'FM999999990.00') || ' is queued for payout.', '/host/earnings');

    v_count := v_count + 1;
  END LOOP;
  RETURN v_count;
END; $function$
;

CREATE OR REPLACE FUNCTION public.search_spaces(p_lat double precision, p_lng double precision, p_radius_km double precision DEFAULT 10, p_starts timestamp with time zone DEFAULT NULL::timestamp with time zone, p_ends timestamp with time zone DEFAULT NULL::timestamp with time zone, p_covered boolean DEFAULT NULL::boolean, p_gated boolean DEFAULT NULL::boolean, p_ev boolean DEFAULT NULL::boolean, p_max_price numeric DEFAULT NULL::numeric)
 RETURNS TABLE(id uuid, title text, address text, lat double precision, lng double precision, price_per_hour numeric, price_per_day numeric, photos text[], is_covered boolean, is_gated boolean, has_ev_charging boolean, has_camera boolean, vehicle_types text[], live_occupancy_status text, distance_km double precision, host_id uuid, cancellation_policy text, is_featured boolean)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    s.id, s.title, s.address,
    ST_Y(s.location::geometry) AS lat,
    ST_X(s.location::geometry) AS lng,
    s.price_per_hour, s.price_per_day, s.photos,
    s.is_covered, s.is_gated, s.has_ev_charging, s.has_camera,
    s.vehicle_types, s.live_occupancy_status,
    ST_Distance(
      s.location,
      ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326)::geography
    ) / 1000.0 AS distance_km,
    s.host_id,
    s.cancellation_policy,
    public.is_host_pro(s.host_id) AS is_featured
  FROM public.parking_spaces s
  WHERE s.is_active = true
    AND ST_DWithin(
      s.location,
      ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326)::geography,
      p_radius_km * 1000
    )
    AND (p_covered   IS NULL OR s.is_covered      = p_covered)
    AND (p_gated     IS NULL OR s.is_gated        = p_gated)
    AND (p_ev        IS NULL OR s.has_ev_charging = p_ev)
    AND (p_max_price IS NULL OR s.price_per_hour <= p_max_price)
    AND (
      p_starts IS NULL OR p_ends IS NULL OR NOT EXISTS (
        SELECT 1 FROM public.bookings b
        WHERE b.space_id = s.id
          AND b.status IN ('confirmed','active')
          AND tstzrange(b.start_time, b.end_time, '[)') && tstzrange(p_starts, p_ends, '[)')
      )
    )
  ORDER BY public.is_host_pro(s.host_id) DESC, distance_km ASC
  LIMIT 100;
$function$
;

CREATE OR REPLACE FUNCTION public.seed_demo_data()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_space1 uuid;
  v_space2 uuid;
  v_space3 uuid;
  v_booking1 uuid;
  v_booking2 uuid;
  v_booking3 uuid;
  v_booking4 uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.has_role(v_uid, 'admin'::app_role) THEN
    RAISE EXCEPTION 'Admins only';
  END IF;

  INSERT INTO public.profiles (id, full_name)
  VALUES (v_uid, 'Demo Admin')
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.parking_spaces (host_id, title, description, address, location, price_per_hour, price_per_day, has_camera, is_gated, is_covered, has_ev_charging, is_active)
  VALUES (v_uid, '[demo] Downtown Covered Garage', 'Secure covered parking near city center.', '123 Market St, Downtown', ST_SetSRID(ST_Point(-74.0060, 40.7128), 4326)::geography, 6.50, 45.00, true, true, true, true, true)
  RETURNING id INTO v_space1;

  INSERT INTO public.parking_spaces (host_id, title, description, address, location, price_per_hour, price_per_day, has_camera, is_gated, is_covered, is_active)
  VALUES (v_uid, '[demo] Airport Long-Stay Lot', 'Perfect for weekend travel.', '500 Airport Rd, Terminal B', ST_SetSRID(ST_Point(-73.7781, 40.6413), 4326)::geography, 3.00, 22.00, true, true, false, true)
  RETURNING id INTO v_space2;

  INSERT INTO public.parking_spaces (host_id, title, description, address, location, price_per_hour, is_active)
  VALUES (v_uid, '[demo] Residential Driveway', 'Quiet suburb driveway, easy access.', '42 Elm Ave, Suburbia', ST_SetSRID(ST_Point(-73.9442, 40.6782), 4326)::geography, 2.25, true)
  RETURNING id INTO v_space3;

  INSERT INTO public.bookings (space_id, renter_id, host_id, start_time, end_time, total_price, status, payment_status, checked_in_at, checked_out_at)
  VALUES (v_space1, v_uid, v_uid, now() - interval '3 days', now() - interval '2 days', 45.00, 'completed', 'paid', now() - interval '3 days', now() - interval '2 days')
  RETURNING id INTO v_booking1;

  INSERT INTO public.bookings (space_id, renter_id, host_id, start_time, end_time, total_price, status, payment_status, checked_in_at)
  VALUES (v_space2, v_uid, v_uid, now() - interval '1 hour', now() + interval '5 hours', 18.00, 'active', 'paid', now() - interval '1 hour')
  RETURNING id INTO v_booking2;

  INSERT INTO public.bookings (space_id, renter_id, host_id, start_time, end_time, total_price, status, payment_status)
  VALUES (v_space1, v_uid, v_uid, now() + interval '2 days', now() + interval '2 days 4 hours', 26.00, 'confirmed', 'paid')
  RETURNING id INTO v_booking3;

  INSERT INTO public.bookings (space_id, renter_id, host_id, start_time, end_time, total_price, status, payment_status)
  VALUES (v_space3, v_uid, v_uid, now() - interval '10 days', now() - interval '9 days', 22.50, 'completed', 'paid')
  RETURNING id INTO v_booking4;

  INSERT INTO public.disputes (booking_id, raised_by, reason, status)
  VALUES (v_booking1, v_uid, 'Space was not as described — gate was broken.', 'open');

  INSERT INTO public.disputes (booking_id, raised_by, reason, status, admin_notes)
  VALUES (v_booking4, v_uid, 'Vehicle was blocked in at checkout.', 'under_review', 'Investigating with host.');

  RETURN jsonb_build_object('spaces', 3, 'bookings', 4, 'disputes', 2);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$function$
;

CREATE OR REPLACE FUNCTION public.settle_booking_payment(p_booking_id uuid, p_transaction_id text, p_amount_charged numeric, p_env text DEFAULT 'live'::text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE b public.bookings; v_fee numeric; v_res numeric := 1; v_earn numeric; v_rate numeric;
        v_pending numeric; v_space text; v_expected numeric;
BEGIN
  SELECT * INTO b FROM public.bookings WHERE id = p_booking_id FOR UPDATE;
  IF b.id IS NULL THEN RAISE EXCEPTION 'Booking not found'; END IF;
  IF b.payment_status IN ('paid','refund_pending','refunded') THEN RETURN 'already_settled'; END IF;

  -- Somebody else confirmed this slot while the driver was paying.
  IF EXISTS (
    SELECT 1 FROM public.bookings o
    WHERE o.space_id = b.space_id AND o.id <> b.id
      AND o.status IN ('confirmed','active')
      AND tstzrange(o.start_time, o.end_time, '[)') && tstzrange(b.start_time, b.end_time, '[)')
  ) THEN
    UPDATE public.bookings SET
      status = 'cancelled', payment_status = 'refund_pending',
      cancelled_at = now(), cancellation_reason = 'Slot was taken before payment completed',
      amount_charged = COALESCE(p_amount_charged, 0),
      refund_amount = COALESCE(p_amount_charged, 0),
      paddle_transaction_id = p_transaction_id, updated_at = now()
    WHERE id = b.id;

    INSERT INTO public.notifications(user_id, kind, title, body, link, booking_id)
    VALUES (b.renter_id, 'payment', 'Reservation unavailable — refund on the way',
      'Another driver confirmed this slot first, so your payment is being refunded in full.',
      '/bookings', b.id);
    RETURN 'conflict';
  END IF;

  v_rate := public.host_commission_rate(b.host_id, p_env);
  v_fee := round(b.total_price * v_rate, 2);
  v_earn := round(b.total_price - v_fee, 2);
  v_expected := round(b.total_price + v_fee + v_res, 2);

  IF p_amount_charged IS NOT NULL AND p_amount_charged < v_expected - 0.05 THEN
    RAISE EXCEPTION 'Underpayment for booking %: charged %, expected %', b.id, p_amount_charged, v_expected;
  END IF;

  UPDATE public.bookings SET
    payment_status = 'paid', status = 'confirmed',
    platform_fee = v_fee, reservation_fee = v_res, host_earning = v_earn,
    amount_charged = COALESCE(p_amount_charged, v_expected),
    paddle_transaction_id = p_transaction_id,
    qr_checkin_code = COALESCE(b.qr_checkin_code, encode(gen_random_bytes(9), 'hex')),
    earnings_clear_at = b.end_time + interval '24 hours',
    hold_expires_at = NULL,
    updated_at = now()
  WHERE id = b.id;

  INSERT INTO public.host_wallets(host_id) VALUES (b.host_id) ON CONFLICT (host_id) DO NOTHING;
  UPDATE public.host_wallets SET
    pending_clearance = pending_clearance + v_earn, updated_at = now()
  WHERE host_id = b.host_id RETURNING pending_clearance INTO v_pending;

  INSERT INTO public.wallet_transactions(host_id, booking_id, kind, amount, balance_after, note)
  VALUES (b.host_id, b.id, 'earning_pending', v_earn, v_pending,
    'Booking paid — held in clearance until 24h after the stay (net of ' || round(v_rate*100) || '% commission)');

  SELECT title INTO v_space FROM public.parking_spaces WHERE id = b.space_id;

  INSERT INTO public.notifications(user_id, kind, title, body, link, booking_id) VALUES
    (b.renter_id, 'booking_confirmed', 'Booking confirmed',
      'Your payment went through. Your check-in code is ready for ' || COALESCE(v_space,'your space') || '.', '/bookings', b.id),
    (b.host_id, 'payment', 'You earned ' || to_char(v_earn, 'FM999999990.00'),
      'A booking for ' || COALESCE(v_space,'your space') || ' was paid. Funds clear 24h after the stay ends.', '/host/earnings', b.id);

  RETURN 'settled';
END; $function$
;

CREATE OR REPLACE FUNCTION public.submit_review(p_booking_id uuid, p_rating integer, p_comment text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_b record;
  v_review_id uuid;
  v_avg numeric;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF p_rating < 1 OR p_rating > 5 THEN RAISE EXCEPTION 'Rating must be 1..5'; END IF;

  SELECT * INTO v_b FROM public.bookings WHERE id = p_booking_id;
  IF v_b.id IS NULL THEN RAISE EXCEPTION 'Booking not found'; END IF;
  IF v_uid <> v_b.renter_id THEN RAISE EXCEPTION 'Only renter can review'; END IF;
  IF v_b.status <> 'completed' THEN RAISE EXCEPTION 'Booking not completed yet'; END IF;

  IF EXISTS (SELECT 1 FROM public.reviews WHERE booking_id = p_booking_id AND reviewer_id = v_uid) THEN
    RAISE EXCEPTION 'Already reviewed';
  END IF;

  INSERT INTO public.reviews (booking_id, reviewer_id, reviewee_id, space_id, rating, comment)
  VALUES (p_booking_id, v_uid, v_b.host_id, v_b.space_id, p_rating, NULLIF(p_comment,''))
  RETURNING id INTO v_review_id;

  SELECT AVG(rating)::numeric(3,2) INTO v_avg
    FROM public.reviews WHERE reviewee_id = v_b.host_id;

  UPDATE public.profiles
     SET rating = COALESCE(v_avg, 0),
         trust_score = LEAST(100, 50 + LEAST(50, total_bookings * 2) + (COALESCE(v_avg,0)::int * 2))
   WHERE id = v_b.host_id;

  RETURN v_review_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.users_share_booking(_a uuid, _b uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.bookings b
    WHERE (b.renter_id = _a AND b.host_id = _b)
       OR (b.renter_id = _b AND b.host_id = _a)
  );
$function$
;


-- ============ TRIGGERS ============
CREATE TRIGGER booking_activity AFTER INSERT OR UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION log_booking_activity();
CREATE TRIGGER trg_bookings_updated_at BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notify_booking_insert AFTER INSERT ON public.bookings FOR EACH ROW EXECUTE FUNCTION notify_on_booking();
CREATE TRIGGER trg_notify_booking_update AFTER UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION notify_on_booking();
CREATE TRIGGER trg_disputes_updated_at BEFORE UPDATE ON public.disputes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_log_dispute_event AFTER INSERT OR UPDATE ON public.disputes FOR EACH ROW EXECUTE FUNCTION log_dispute_event();
CREATE TRIGGER host_wallets_updated_at BEFORE UPDATE ON public.host_wallets FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notify_on_message AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION notify_on_message();
CREATE TRIGGER trg_spaces_updated_at BEFORE UPDATE ON public.parking_spaces FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER payout_requests_updated_at BEFORE UPDATE ON public.payout_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER review_activity AFTER INSERT ON public.reviews FOR EACH ROW EXECUTE FUNCTION log_review_activity();
CREATE TRIGGER support_tickets_updated_at BEFORE UPDATE ON public.support_tickets FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============ ROW LEVEL SECURITY ============
alter table public.activity_log enable row level security;
alter table public.availability_slots enable row level security;
alter table public.bookings enable row level security;
alter table public.dispute_events enable row level security;
alter table public.disputes enable row level security;
alter table public.host_wallets enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.parking_spaces enable row level security;
alter table public.payout_requests enable row level security;
alter table public.profile_contacts enable row level security;
alter table public.profiles enable row level security;
alter table public.reviews enable row level security;
alter table public.subscriptions enable row level security;
alter table public.support_tickets enable row level security;
alter table public.user_roles enable row level security;
alter table public.wallet_transactions enable row level security;

create policy "Admins view all activity" on public.activity_log as PERMISSIVE for SELECT to authenticated using (has_role(auth.uid(), 'admin'::app_role));
create policy "Users insert own activity" on public.activity_log as PERMISSIVE for INSERT to authenticated with check ((auth.uid() = user_id));
create policy "Users view own activity" on public.activity_log as PERMISSIVE for SELECT to authenticated using ((auth.uid() = user_id));
create policy "Hosts manage own slots" on public.availability_slots as PERMISSIVE for ALL to public using ((space_id IN ( SELECT parking_spaces.id
   FROM parking_spaces
  WHERE (parking_spaces.host_id = auth.uid()))));
create policy "Hosts view own slots" on public.availability_slots as PERMISSIVE for SELECT to authenticated using ((space_id IN ( SELECT parking_spaces.id
   FROM parking_spaces
  WHERE (parking_spaces.host_id = auth.uid()))));
create policy "Signed-in users view slots of active spaces" on public.availability_slots as PERMISSIVE for SELECT to authenticated using ((space_id IN ( SELECT parking_spaces.id
   FROM parking_spaces
  WHERE (parking_spaces.is_active = true))));
create policy "Admins view all bookings" on public.bookings as PERMISSIVE for SELECT to authenticated using (has_role(auth.uid(), 'admin'::app_role));
create policy "Users view own bookings" on public.bookings as PERMISSIVE for SELECT to authenticated using (((auth.uid() = renter_id) OR (auth.uid() = host_id)));
create policy "Admins view all dispute events" on public.dispute_events as PERMISSIVE for SELECT to authenticated using (has_role(auth.uid(), 'admin'::app_role));
create policy "Involved parties view dispute events" on public.dispute_events as PERMISSIVE for SELECT to authenticated using ((dispute_id IN ( SELECT d.id
   FROM (disputes d
     JOIN bookings b ON ((b.id = d.booking_id)))
  WHERE ((b.renter_id = auth.uid()) OR (b.host_id = auth.uid())))));
create policy "Admins update disputes" on public.disputes as PERMISSIVE for UPDATE to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "Admins view all disputes" on public.disputes as PERMISSIVE for SELECT to authenticated using (has_role(auth.uid(), 'admin'::app_role));
create policy "Involved parties view disputes" on public.disputes as PERMISSIVE for SELECT to authenticated using ((booking_id IN ( SELECT bookings.id
   FROM bookings
  WHERE ((bookings.renter_id = auth.uid()) OR (bookings.host_id = auth.uid())))));
create policy "Users raise disputes on own bookings" on public.disputes as PERMISSIVE for INSERT to authenticated with check (((auth.uid() = raised_by) AND (booking_id IN ( SELECT bookings.id
   FROM bookings
  WHERE ((bookings.renter_id = auth.uid()) OR (bookings.host_id = auth.uid()))))));
create policy "Hosts view own wallet" on public.host_wallets as PERMISSIVE for SELECT to authenticated using (((auth.uid() = host_id) OR has_role(auth.uid(), 'admin'::app_role)));
create policy "messages insert parties" on public.messages as PERMISSIVE for INSERT to authenticated with check (((sender_id = auth.uid()) AND is_booking_party(booking_id, auth.uid())));
create policy "messages mark read" on public.messages as PERMISSIVE for UPDATE to authenticated using (is_booking_party(booking_id, auth.uid())) with check (is_booking_party(booking_id, auth.uid()));
create policy "messages read parties" on public.messages as PERMISSIVE for SELECT to authenticated using (is_booking_party(booking_id, auth.uid()));
create policy "own notifications delete" on public.notifications as PERMISSIVE for DELETE to authenticated using ((auth.uid() = user_id));
create policy "own notifications read" on public.notifications as PERMISSIVE for SELECT to authenticated using ((auth.uid() = user_id));
create policy "own notifications update" on public.notifications as PERMISSIVE for UPDATE to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Active spaces are viewable by everyone" on public.parking_spaces as PERMISSIVE for SELECT to anon, authenticated using (((is_active = true) OR (host_id = auth.uid())));
create policy "Hosts delete own spaces" on public.parking_spaces as PERMISSIVE for DELETE to authenticated using ((auth.uid() = host_id));
create policy "Hosts insert own spaces" on public.parking_spaces as PERMISSIVE for INSERT to authenticated with check ((auth.uid() = host_id));
create policy "Hosts update own spaces" on public.parking_spaces as PERMISSIVE for UPDATE to authenticated using ((auth.uid() = host_id)) with check ((auth.uid() = host_id));
create policy "Hosts view own payouts" on public.payout_requests as PERMISSIVE for SELECT to authenticated using (((auth.uid() = host_id) OR has_role(auth.uid(), 'admin'::app_role)));
create policy "Booking counterparties view phone" on public.profile_contacts as PERMISSIVE for SELECT to authenticated using (users_share_booking(auth.uid(), user_id));
create policy "Owner manages own phone" on public.profile_contacts as PERMISSIVE for ALL to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Profiles visible to self, counterparties and admins" on public.profiles as PERMISSIVE for SELECT to authenticated using (((id = auth.uid()) OR users_share_booking(auth.uid(), id) OR has_role(auth.uid(), 'admin'::app_role)));
create policy "Users can insert their own profile" on public.profiles as PERMISSIVE for INSERT to public with check ((auth.uid() = id));
create policy "Users can update their own profile" on public.profiles as PERMISSIVE for UPDATE to public using ((auth.uid() = id));
create policy "Anyone can view reviews" on public.reviews as PERMISSIVE for SELECT to public using (true);
create policy "Reviews viewable by everyone" on public.reviews as PERMISSIVE for SELECT to public using (true);
create policy "Users view own subscription" on public.subscriptions as PERMISSIVE for SELECT to authenticated using ((auth.uid() = user_id));
create policy "Admins update tickets" on public.support_tickets as PERMISSIVE for UPDATE to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "Anyone can submit a support ticket" on public.support_tickets as PERMISSIVE for INSERT to anon, authenticated with check (((user_id IS NULL) OR (user_id = auth.uid())));
create policy "Users view own tickets" on public.support_tickets as PERMISSIVE for SELECT to authenticated using (((user_id = auth.uid()) OR has_role(auth.uid(), 'admin'::app_role)));
create policy "Admins view all roles" on public.user_roles as PERMISSIVE for SELECT to authenticated using (has_role(auth.uid(), 'admin'::app_role));
create policy "Users view own roles" on public.user_roles as PERMISSIVE for SELECT to authenticated using ((auth.uid() = user_id));
create policy "Hosts view own ledger" on public.wallet_transactions as PERMISSIVE for SELECT to authenticated using (((auth.uid() = host_id) OR has_role(auth.uid(), 'admin'::app_role)));
create policy "No direct ledger deletes" on public.wallet_transactions as RESTRICTIVE for DELETE to anon, authenticated using (false);
create policy "No direct ledger updates" on public.wallet_transactions as RESTRICTIVE for UPDATE to anon, authenticated using (false) with check (false);
create policy "No direct ledger writes" on public.wallet_transactions as RESTRICTIVE for INSERT to anon, authenticated with check (false);

-- ============ GRANTS ============

revoke all on function public.cancellation_cutoff_hours(_policy text) from public, anon, authenticated;
revoke all on function public.get_refund_job(p_booking_id uuid) from public, anon, authenticated;
revoke all on function public.grant_role(p_user_id uuid, p_role app_role) from public, anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.has_active_subscription(user_uuid uuid, check_env text) from public, anon, authenticated;
revoke all on function public.host_commission_rate(_host_id uuid, _env text) from public, anon, authenticated;
revoke all on function public.is_host_pro(_user_id uuid, _env text) from public, anon, authenticated;
revoke all on function public.log_booking_activity() from public, anon, authenticated;
revoke all on function public.log_dispute_event() from public, anon, authenticated;
revoke all on function public.log_review_activity() from public, anon, authenticated;
revoke all on function public.mark_booking_refunded(p_booking_id uuid, p_refund_id text) from public, anon, authenticated;
revoke all on function public.mark_booking_refunded_by_transaction(p_transaction_id text) from public, anon, authenticated;
revoke all on function public.notify_on_booking() from public, anon, authenticated;
revoke all on function public.notify_on_message() from public, anon, authenticated;
revoke all on function public.release_cleared_earnings() from public, anon, authenticated;
revoke all on function public.run_monthly_payouts() from public, anon, authenticated;
revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.settle_booking_payment(p_booking_id uuid, p_transaction_id text, p_amount_charged numeric, p_env text) from public, anon, authenticated;
