#!/usr/bin/env bash
# Regenerates supabase/schema.sql — the portable schema you run against your own
# Supabase project. Requires PG* env vars pointing at the source database.
set -euo pipefail
OUT="${1:-supabase/schema.sql}"
mkdir -p "$(dirname "$OUT")"

q() { psql -At -F '' -c "$1"; }

{
  echo "-- LumoroX Park — portable database schema."
  echo "-- Generated by scripts/export-schema.sh. Run this in the SQL editor of"
  echo "-- your own Supabase project (once, on an empty project)."
  echo
  echo 'create extension if not exists "uuid-ossp";'
  echo 'create extension if not exists postgis;'
  echo 'create extension if not exists pgcrypto;'
  echo

  echo "-- ============ ENUM TYPES ============"
  q "select format('do \$\$ begin create type public.%I as enum (%s); exception when duplicate_object then null; end \$\$;', t.typname, string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder))
     from pg_type t join pg_enum e on e.enumtypid=t.oid join pg_namespace n on n.oid=t.typnamespace
     where n.nspname='public' group by t.typname;"
  echo

  echo "-- ============ TABLES ============"
  q "select format(E'create table if not exists public.%I (\n%s\n);', c.relname,
        (select string_agg(format('  %I %s%s%s', a.attname,
            format_type(a.atttypid, a.atttypmod),
            case when a.attnotnull then ' not null' else '' end,
            coalesce(' default ' || pg_get_expr(d.adbin, d.adrelid), '')), E',\n' order by a.attnum)
         from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum
         where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped))
     from pg_class c join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='public' and c.relkind='r' and c.relname<>'spatial_ref_sys'
     order by c.relname;"
  echo

  echo "-- ============ CONSTRAINTS ============"
  q "select format('alter table public.%I add constraint %I %s;', c.relname, con.conname, pg_get_constraintdef(con.oid))
     from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='public' and c.relname<>'spatial_ref_sys' order by con.contype desc, c.relname;"
  echo

  echo "-- ============ INDEXES ============"
  q "select indexdef || ';' from pg_indexes where schemaname='public' and tablename<>'spatial_ref_sys'
     and indexname not in (select conname from pg_constraint) order by tablename, indexname;"
  echo

  echo "-- ============ FUNCTIONS ============"
  q "select pg_get_functiondef(p.oid) || E';\n'
     from pg_proc p join pg_namespace n on n.oid=p.pronamespace
     where n.nspname='public'
       and p.oid not in (select d.objid from pg_depend d join pg_extension e on e.oid=d.refobjid where d.deptype='e')
     order by p.proname;"
  echo

  echo "-- ============ TRIGGERS ============"
  q "select pg_get_triggerdef(t.oid) || ';'
     from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='public' and not t.tgisinternal order by c.relname, t.tgname;"
  echo

  echo "-- ============ ROW LEVEL SECURITY ============"
  q "select format('alter table public.%I enable row level security;', c.relname)
     from pg_class c join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='public' and c.relkind='r' and c.relrowsecurity order by c.relname;"
  echo
  q "select format('create policy %I on public.%I as %s for %s to %s%s%s;',
        pol.policyname, pol.tablename, pol.permissive, pol.cmd, array_to_string(pol.roles, ', '),
        coalesce(' using (' || pol.qual || ')',''), coalesce(' with check (' || pol.with_check || ')',''))
     from pg_policies pol where pol.schemaname='public' order by pol.tablename, pol.policyname;"
  echo

  echo "-- ============ GRANTS ============"
  q "select format('grant %s on public.%I to %I;', string_agg(distinct privilege_type, ', '), table_name, grantee)
     from information_schema.role_table_grants
     where table_schema='public' and grantee in ('anon','authenticated','service_role') and table_name<>'spatial_ref_sys'
     group by table_name, grantee order by table_name, grantee;"
  echo
  q "select format('revoke all on function public.%I(%s) from public, anon, authenticated;', p.proname, pg_get_function_identity_arguments(p.oid))
     from pg_proc p join pg_namespace n on n.oid=p.pronamespace
     where n.nspname='public'
       and p.oid not in (select d.objid from pg_depend d join pg_extension e on e.oid=d.refobjid where d.deptype='e')
       and not has_function_privilege('authenticated', p.oid, 'EXECUTE')
     order by p.proname;"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
